name: Upterm runner

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Select runner OS'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      limit_to_actor:
        description: 'Limit SSH access to my GitHub SSH keys'
        required: false
        type: boolean
        default: true

jobs:
  vm:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: julia-actions/setup-julia@v3

      - name: Start upterm session
        uses: owenthereal/action-upterm@v1
        with:
          wait-timeout-minutes: 15
          limit-access-to-actor: ${{ inputs.limit_to_actor }}
